[package]
name = "rust-dcp-membership-couchbase"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bytes.workspace = true
rust-dcp-core = { path = "../rust-dcp-core", version = "0.1.0" }
rust-dcp-protocol = { path = "../rust-dcp-protocol", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
